FROM alpine:latest

RUN apk update && \
    apk install -y \
    libboost-dev \
    libboost-all-dev \
    git \
    curl \
    cmake \
    bash \
    gcc g++ \
    python3-pip python3-venv 

RUN python3 -m venv .venv
COPY requirements-swmm.txt .

RUN . /.venv/bin/activate && pip install -r requirements-swmm.txt


ENTRYPOINT [ "/bin/bash" ]
