name: Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04]
        requirements: [requirements-swmm.txt]
        include:
          - os: windows-2022
            defaults:
              run:
                shell: cmd
                working-directory: ./windows

          - os: ubuntu-22.04
            defaults:
              run:
                shell: bash
                working-directory: ./linux

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.defaults.run.shell }}
        working-directory: ${{ matrix.defaults.run.working-directory }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pyswmm/build_swmm
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}